### ISSUE TITLE
Error not utf-8 in comment fieldkey.

### ISSUE THREAD

**Issue by buldi** [neumond/django-dia#1]
... ./django-dia/management/commands/make_diagram.py", line 64, in make_dia_attribute
    value = u'#{}#'.format(value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 9: ordinal not in range(128)

**Comment by neumond** [comment]
Can you point me how to reproduce your result? I've used lots of unicode in comments, but got no such error. Printdebug show that there comes lots of 'str' and 'unicode', but .format handles that fine.

**Comment by buldi** [comment]
This is error ...

class ...  (models.Model):
    ...
    Opis_krotki = models.TextField(verbose_name="Krótki opis produktu", null=True)
    ...


Correct ..
class ...  (models.Model):
    ...
    Opis_krotki = models.TextField(verbose_name=u"Krótki opis produktu", null=True)
    ...
