### ISSUE TITLE
Subdirectory's application schema

### ISSUE THREAD

**Issue by pawelmarkowski** [neumond/django-dia#7]
I have "apps" dir for custom applications and I tried to generate schema for specified app by executing:
python manage.py make_diagram -e -o scheme apps.xparts
python manage.py make_diagram -e -o scheme xparts

and I received an error:
manage.py make_diagram: error: unrecognized arguments: xparts
or apps.xparts

**Comment by neumond** [comment]
Missed this thing while porting to new argparse-like arguments. Thanks for report. Please update to 0.3.4.
